eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: service-client-provider
#swagger:
#  enabled: true
#  title: 综合服务接口
#  description: 综合服务接口desc
#  base-package: com.mdjin
#  base-path: /**
#  exclude-path: /basic-error-controller
#  version: @project.version@
#  contact:
#    email: jinmaodong@outloo.com
#    name: 金茂东
#
